robot_base_frame: base_link

transform_tolerance: 0.2

update_frequency: 10.0
publish_frequency: 5.0 # for debug only

track_unknown_space: true

obstacle_range: 4.0
raytrace_range: 8.0

footprint: [[-0.200, -0.125], [-0.200, 0.125], [0.250, 0.125], [0.250, -0.125]]

static:
  map_topic: map
  trinary_costmap: true
  lethal_cost_threshold: 65
  track_unknown_space: true

obstacles_laser:
  observation_sources: "laser_scan_sensor"
  laser_scan_sensor:
    data_type: LaserScan
    topic: /rplidar/scan
    marking: true
    clearing: true
  rgbd_camera:
    data_type: PointCloud2
    topic: /camera/aligned_depth_to_color/points
    clearing: true
    marking: true
    max_obstacle_height: 0.20
    min_obstacle_height: 0.02
    obstacle_range: 2.5
    raytrace_range: 3.0

inflation:
  inflation_radius: 0.2
