global_costmap:
  width: 20.0
  height: 20.0
  global_frame: map
  rolling_window: false
  inflation_radius: 0.4
  plugins:
    - name: static
      type: costmap_2d::StaticLayer
    - name: inflation
      type: costmap_2d::InflationLayer
