base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:
  odom_topic: odom
  map_frame: map

  # Trajectory

  teb_autosize: true
  dt_ref: 0.10
  dt_hysteresis: 0.01
  global_plan_overwrite_orientation: false
  max_global_plan_lookahead_dist: 0
  feasibility_check_no_poses: 10
  allow_init_with_backwards_motion: true
  force_reinit_new_goal_dist: 0.05
  publish_feedback: true # only for debugging

  # Robot

  max_vel_x: 0.5
  max_vel_x_backwards: 0.5
  max_vel_y: 0.5
  max_vel_theta: 0.5
  acc_lim_x: 5.0
  acc_lim_y: 5.0
  acc_lim_theta: 10.0
  min_turning_radius: 0.0
  wheelbase: 0.0

  footprint_model:
    type: "polygon"
    vertices: [[-0.160, -0.120], [-0.160, 0.120], [0.160, 0.120], [0.160, -0.120]]

  # GoalTolerance

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  free_goal_vel: true

  # Obstacles

  min_obstacle_dist: 0.01
  inflation_dist: 0.4
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 5.0
  obstacle_poses_affected: 10
  obstacle_association_force_inclusion_factor: 30.0
  obstacle_association_cutoff_factor: 100.0

  # Optimization

  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.1
  weight_max_vel_x: 1
  weight_max_vel_y: 1
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_y: 3
  weight_acc_lim_theta: 3
  weight_kinematics_nh: 0
  weight_kinematics_forward_drive: 0
  weight_kinematics_turning_radius: 0
  weight_optimaltime: 20
  weight_obstacle: 50

  # Homotopy Class Planner

  enable_homotopy_class_planning: false
  enable_multithreading: true
  visualize_hc_graph: true

  # Costmap converter
  #costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
  costmap_converter_rate: 10
  costmap_converter_spin_thread: true
