GlobalPlanner:
# 指定是否允许路径规划器在未知空间创建路径规划。
  allow_unknown: false
# 路径规划器目标点的公差范围。
  default_tolerance: 1.0
# 如果为ture，则使用dijkstra算法。 否则使用A *算法。
  use_dijkstra: true
# 如果为真，则使用势的二次逼近。否则，使用更简单的计算。
  use_quadratic: true  
# 如果为true，沿着栅格边界创建路径。 否则，使用梯度下降的方法。
  use_grid_path: false
# 概述全球成本地图的致命障碍。对于非静态(滚动窗口)全局成本图的使用，需要将其设置为false
  #outline_map: false
  
# 如果你想要global_planner准确反映navfn的行为，此项设置为true。
  old_navfn_behavior: false
# 指定是否可视化通过PointCloud2计算的潜在区域。
  visualize_potential: false
# 发布潜在Costmap(动态重新配置)
  publish_potential: true
# 致命代价(动态重新配置)
  lethal_cost: 253
# 中性成本(动态重新配置)
  neutral_cost: 50
# 从costmap乘以每个成本的因素(动态重新配置)
  cost_factor: 3.0
# 如何设置每个点的方向
  orientation_mode: 0
# 使用哪个窗口根据方向模式指定的位置导数来确定方向(动态重新配置)
  orientation_window_size: 1
